
# Site settings
title: Robert Nolan / Product Designer & Software Engineer
name: Robert Nolan
email: hello@rnolan.com
location: Saint Louis, MO
location_map_url: "https://goo.gl/maps/pVVN9zgtSL82"
description: > # this means to ignore newlines until "baseurl:"
  Robert Nolan is a hybrid product designer & software engineer living in St. Louis, MO.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rnolan.com" # the base hostname & protocol for your site
social_networks:
-
  name: Github
  profile_id: rnolan3
  url: "https://github.com/"
-
  name: Linkedin
  profile_id: rnolan3
  url: "https://www.linkedin.com/in/"

# Endeavors
endeavors:
-
  title: Draw It to Know It
  url: "https://drawittoknowit.com/"
  description: A learning tool for the medical sciences.
-
  title: StickyList
  url: "https://github.com/rnolan3/sticky-list"
  description: An agnostic javascript module.
-
  title: DOM Destroyer
  archived: true,
  url: "https://github.com/rnolan3/dom_destroyer"
  description: Experiemental game that explored OO programming with javascript.
-
  title: Noboleis Vineyards
  url: "http://noboleisvineyards.com/"
  description: A family owned vineyard in Augusta, MO

# Build settings
markdown: kramdown
